# Generated by Django 3.1.1 on 2020-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_url', models.CharField(max_length=200)),
                ('contents_name', models.CharField(max_length=100)),
                ('contents_image', models.CharField(max_length=200)),
            ],
        ),
    ]
